/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicPublicLayoutRouteImport } from './routes/(public)/_publicLayout'
import { Route as appAppLayoutRouteImport } from './routes/(app)/_appLayout'
import { Route as publicPublicLayoutIndexRouteImport } from './routes/(public)/_publicLayout.index'
import { Route as appAppLayoutCreateSupplierRouteImport } from './routes/(app)/_appLayout.create-supplier'
import { Route as appAppLayoutEventsIndexRouteImport } from './routes/(app)/_appLayout.events.index'
import { Route as publicPublicLayoutAuthPathnameRouteImport } from './routes/(public)/_publicLayout.auth.$pathname'
import { Route as appAppLayoutEventsEventIdRouteImport } from './routes/(app)/_appLayout.events.$eventId'
import { Route as appAppLayoutEEventIdRouteImport } from './routes/(app)/_appLayout.e.$eventId'
import { Route as appAppLayoutAccountPathnameRouteImport } from './routes/(app)/_appLayout.account.$pathname'

const publicPublicLayoutRoute = publicPublicLayoutRouteImport.update({
  id: '/(public)/_publicLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppLayoutRoute = appAppLayoutRouteImport.update({
  id: '/(app)/_appLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPublicLayoutIndexRoute = publicPublicLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicPublicLayoutRoute,
} as any)
const appAppLayoutCreateSupplierRoute =
  appAppLayoutCreateSupplierRouteImport.update({
    id: '/create-supplier',
    path: '/create-supplier',
    getParentRoute: () => appAppLayoutRoute,
  } as any)
const appAppLayoutEventsIndexRoute = appAppLayoutEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => appAppLayoutRoute,
} as any)
const publicPublicLayoutAuthPathnameRoute =
  publicPublicLayoutAuthPathnameRouteImport.update({
    id: '/auth/$pathname',
    path: '/auth/$pathname',
    getParentRoute: () => publicPublicLayoutRoute,
  } as any)
const appAppLayoutEventsEventIdRoute =
  appAppLayoutEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => appAppLayoutRoute,
  } as any)
const appAppLayoutEEventIdRoute = appAppLayoutEEventIdRouteImport.update({
  id: '/e/$eventId',
  path: '/e/$eventId',
  getParentRoute: () => appAppLayoutRoute,
} as any)
const appAppLayoutAccountPathnameRoute =
  appAppLayoutAccountPathnameRouteImport.update({
    id: '/account/$pathname',
    path: '/account/$pathname',
    getParentRoute: () => appAppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/create-supplier': typeof appAppLayoutCreateSupplierRoute
  '/': typeof publicPublicLayoutIndexRoute
  '/account/$pathname': typeof appAppLayoutAccountPathnameRoute
  '/e/$eventId': typeof appAppLayoutEEventIdRoute
  '/events/$eventId': typeof appAppLayoutEventsEventIdRoute
  '/auth/$pathname': typeof publicPublicLayoutAuthPathnameRoute
  '/events': typeof appAppLayoutEventsIndexRoute
}
export interface FileRoutesByTo {
  '/create-supplier': typeof appAppLayoutCreateSupplierRoute
  '/': typeof publicPublicLayoutIndexRoute
  '/account/$pathname': typeof appAppLayoutAccountPathnameRoute
  '/e/$eventId': typeof appAppLayoutEEventIdRoute
  '/events/$eventId': typeof appAppLayoutEventsEventIdRoute
  '/auth/$pathname': typeof publicPublicLayoutAuthPathnameRoute
  '/events': typeof appAppLayoutEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/_appLayout': typeof appAppLayoutRouteWithChildren
  '/(public)/_publicLayout': typeof publicPublicLayoutRouteWithChildren
  '/(app)/_appLayout/create-supplier': typeof appAppLayoutCreateSupplierRoute
  '/(public)/_publicLayout/': typeof publicPublicLayoutIndexRoute
  '/(app)/_appLayout/account/$pathname': typeof appAppLayoutAccountPathnameRoute
  '/(app)/_appLayout/e/$eventId': typeof appAppLayoutEEventIdRoute
  '/(app)/_appLayout/events/$eventId': typeof appAppLayoutEventsEventIdRoute
  '/(public)/_publicLayout/auth/$pathname': typeof publicPublicLayoutAuthPathnameRoute
  '/(app)/_appLayout/events/': typeof appAppLayoutEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/create-supplier'
    | '/'
    | '/account/$pathname'
    | '/e/$eventId'
    | '/events/$eventId'
    | '/auth/$pathname'
    | '/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/create-supplier'
    | '/'
    | '/account/$pathname'
    | '/e/$eventId'
    | '/events/$eventId'
    | '/auth/$pathname'
    | '/events'
  id:
    | '__root__'
    | '/(app)/_appLayout'
    | '/(public)/_publicLayout'
    | '/(app)/_appLayout/create-supplier'
    | '/(public)/_publicLayout/'
    | '/(app)/_appLayout/account/$pathname'
    | '/(app)/_appLayout/e/$eventId'
    | '/(app)/_appLayout/events/$eventId'
    | '/(public)/_publicLayout/auth/$pathname'
    | '/(app)/_appLayout/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appAppLayoutRoute: typeof appAppLayoutRouteWithChildren
  publicPublicLayoutRoute: typeof publicPublicLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/_publicLayout': {
      id: '/(public)/_publicLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicPublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_appLayout': {
      id: '/(app)/_appLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_publicLayout/': {
      id: '/(public)/_publicLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicPublicLayoutIndexRouteImport
      parentRoute: typeof publicPublicLayoutRoute
    }
    '/(app)/_appLayout/create-supplier': {
      id: '/(app)/_appLayout/create-supplier'
      path: '/create-supplier'
      fullPath: '/create-supplier'
      preLoaderRoute: typeof appAppLayoutCreateSupplierRouteImport
      parentRoute: typeof appAppLayoutRoute
    }
    '/(app)/_appLayout/events/': {
      id: '/(app)/_appLayout/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof appAppLayoutEventsIndexRouteImport
      parentRoute: typeof appAppLayoutRoute
    }
    '/(public)/_publicLayout/auth/$pathname': {
      id: '/(public)/_publicLayout/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof publicPublicLayoutAuthPathnameRouteImport
      parentRoute: typeof publicPublicLayoutRoute
    }
    '/(app)/_appLayout/events/$eventId': {
      id: '/(app)/_appLayout/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof appAppLayoutEventsEventIdRouteImport
      parentRoute: typeof appAppLayoutRoute
    }
    '/(app)/_appLayout/e/$eventId': {
      id: '/(app)/_appLayout/e/$eventId'
      path: '/e/$eventId'
      fullPath: '/e/$eventId'
      preLoaderRoute: typeof appAppLayoutEEventIdRouteImport
      parentRoute: typeof appAppLayoutRoute
    }
    '/(app)/_appLayout/account/$pathname': {
      id: '/(app)/_appLayout/account/$pathname'
      path: '/account/$pathname'
      fullPath: '/account/$pathname'
      preLoaderRoute: typeof appAppLayoutAccountPathnameRouteImport
      parentRoute: typeof appAppLayoutRoute
    }
  }
}

interface appAppLayoutRouteChildren {
  appAppLayoutCreateSupplierRoute: typeof appAppLayoutCreateSupplierRoute
  appAppLayoutAccountPathnameRoute: typeof appAppLayoutAccountPathnameRoute
  appAppLayoutEEventIdRoute: typeof appAppLayoutEEventIdRoute
  appAppLayoutEventsEventIdRoute: typeof appAppLayoutEventsEventIdRoute
  appAppLayoutEventsIndexRoute: typeof appAppLayoutEventsIndexRoute
}

const appAppLayoutRouteChildren: appAppLayoutRouteChildren = {
  appAppLayoutCreateSupplierRoute: appAppLayoutCreateSupplierRoute,
  appAppLayoutAccountPathnameRoute: appAppLayoutAccountPathnameRoute,
  appAppLayoutEEventIdRoute: appAppLayoutEEventIdRoute,
  appAppLayoutEventsEventIdRoute: appAppLayoutEventsEventIdRoute,
  appAppLayoutEventsIndexRoute: appAppLayoutEventsIndexRoute,
}

const appAppLayoutRouteWithChildren = appAppLayoutRoute._addFileChildren(
  appAppLayoutRouteChildren,
)

interface publicPublicLayoutRouteChildren {
  publicPublicLayoutIndexRoute: typeof publicPublicLayoutIndexRoute
  publicPublicLayoutAuthPathnameRoute: typeof publicPublicLayoutAuthPathnameRoute
}

const publicPublicLayoutRouteChildren: publicPublicLayoutRouteChildren = {
  publicPublicLayoutIndexRoute: publicPublicLayoutIndexRoute,
  publicPublicLayoutAuthPathnameRoute: publicPublicLayoutAuthPathnameRoute,
}

const publicPublicLayoutRouteWithChildren =
  publicPublicLayoutRoute._addFileChildren(publicPublicLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  appAppLayoutRoute: appAppLayoutRouteWithChildren,
  publicPublicLayoutRoute: publicPublicLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
