name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  cancel-in-progress: true
  group: ci-${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 24

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Type-check
        run: pnpm type-check

      - name: Tests
        run: pnpm test
